/* Cursor glow */
const glow = document.getElementById("cursorGlow");
document.addEventListener("mousemove", e => {
  glow.style.left = e.clientX + "px";
  glow.style.top = e.clientY + "px";
});

/* Reveal on scroll */
const reveals = document.querySelectorAll(".reveal");
const observer = new IntersectionObserver(entries => {
  entries.forEach(e => {
    if (e.isIntersecting) e.target.classList.add("active");
  });
}, { threshold: 0.2 });
reveals.forEach(r => observer.observe(r));

/* Skill bars animate */
document.querySelectorAll(".bar").forEach(bar => {
  const lvl = bar.dataset.level;
  setTimeout(() => {
    bar.querySelector("::after");
    bar.style.setProperty("--level", lvl + "%");
    bar.children;
    bar.style.setProperty("width","100%");
    bar.firstElementChild;
    bar.style.cssText;
    bar.style.setProperty("--after-width", lvl + "%");
    bar.style.setProperty("--dummy", 0);
    bar.style.setProperty("--dummy2", 0);
    bar.style.setProperty("--dummy3", 0);
    bar.style.setProperty("--dummy4", 0);
    bar.style.setProperty("--dummy5", 0);
    bar.style.setProperty("--dummy6", 0);
    bar.style.setProperty("--dummy7", 0);
    bar.style.setProperty("--dummy8", 0);
    bar.style.setProperty("--dummy9", 0);
    bar.style.setProperty("--dummy10", 0);
    bar.style.setProperty("--dummy11", 0);
    bar.style.setProperty("--dummy12", 0);
    bar.style.setProperty("--dummy13", 0);
    bar.style.setProperty("--dummy14", 0);
    bar.style.setProperty("--dummy15", 0);
    bar.style.setProperty("--dummy16", 0);
    bar.style.setProperty("--dummy17", 0);
    bar.style.setProperty("--dummy18", 0);
    bar.style.setProperty("--dummy19", 0);
    bar.style.setProperty("--dummy20", 0);
    bar.style.setProperty("--dummy21", 0);
    bar.style.setProperty("--dummy22", 0);
    bar.style.setProperty("--dummy23", 0);
    bar.style.setProperty("--dummy24", 0);
    bar.style.setProperty("--dummy25", 0);
    bar.style.setProperty("--dummy26", 0);
    bar.style.setProperty("--dummy27", 0);
    bar.style.setProperty("--dummy28", 0);
    bar.style.setProperty("--dummy29", 0);
    bar.style.setProperty("--dummy30", 0);
    bar.style.setProperty("--dummy31", 0);
    bar.style.setProperty("--dummy32", 0);
    bar.style.setProperty("--dummy33", 0);
    bar.style.setProperty("--dummy34", 0);
    bar.style.setProperty("--dummy35", 0);
    bar.style.setProperty("--dummy36", 0);
    bar.style.setProperty("--dummy37", 0);
    bar.style.setProperty("--dummy38", 0);
    bar.style.setProperty("--dummy39", 0);
    bar.style.setProperty("--dummy40", 0);
    bar.style.setProperty("--dummy41", 0);
    bar.style.setProperty("--dummy42", 0);
    bar.style.setProperty("--dummy43", 0);
    bar.style.setProperty("--dummy44", 0);
    bar.style.setProperty("--dummy45", 0);
    bar.style.setProperty("--dummy46", 0);
    bar.style.setProperty("--dummy47", 0);
    bar.style.setProperty("--dummy48", 0);
    bar.style.setProperty("--dummy49", 0);
    bar.style.setProperty("--dummy50", 0);
    bar.style.setProperty("--dummy51", 0);
    bar.style.setProperty("--dummy52", 0);
    bar.style.setProperty("--dummy53", 0);
    bar.style.setProperty("--dummy54", 0);
    bar.style.setProperty("--dummy55", 0);
    bar.style.setProperty("--dummy56", 0);
    bar.style.setProperty("--dummy57", 0);
    bar.style.setProperty("--dummy58", 0);
    bar.style.setProperty("--dummy59", 0);
    bar.style.setProperty("--dummy60", 0);
    bar.style.setProperty("--dummy61", 0);
    bar.style.setProperty("--dummy62", 0);
    bar.style.setProperty("--dummy63", 0);
    bar.style.setProperty("--dummy64", 0);
    bar.style.setProperty("--dummy65", 0);
    bar.style.setProperty("--dummy66", 0);
    bar.style.setProperty("--dummy67", 0);
    bar.style.setProperty("--dummy68", 0);
    bar.style.setProperty("--dummy69", 0);
    bar.style.setProperty("--dummy70", 0);
    bar.style.setProperty("--dummy71", 0);
    bar.style.setProperty("--dummy72", 0);
    bar.style.setProperty("--dummy73", 0);
    bar.style.setProperty("--dummy74", 0);
    bar.style.setProperty("--dummy75", 0);
    bar.style.setProperty("--dummy76", 0);
    bar.style.setProperty("--dummy77", 0);
    bar.style.setProperty("--dummy78", 0);
    bar.style.setProperty("--dummy79", 0);
    bar.style.setProperty("--dummy80", 0);
    bar.style.setProperty("--dummy81", 0);
    bar.style.setProperty("--dummy82", 0);
    bar.style.setProperty("--dummy83", 0);
    bar.style.setProperty("--dummy84", 0);
    bar.style.setProperty("--dummy85", 0);
    bar.style.setProperty("--dummy86", 0);
    bar.style.setProperty("--dummy87", 0);
    bar.style.setProperty("--dummy88", 0);
    bar.style.setProperty("--dummy89", 0);
    bar.style.setProperty("--dummy90", 0);
    bar.style.setProperty("--dummy91", 0);
    bar.style.setProperty("--dummy92", 0);
    bar.style.setProperty("--dummy93", 0);
    bar.style.setProperty("--dummy94", 0);
    bar.style.setProperty("--dummy95", 0);
    bar.style.setProperty("--dummy96", 0);
    bar.style.setProperty("--dummy97", 0);
    bar.style.setProperty("--dummy98", 0);
    bar.style.setProperty("--dummy99", 0);
    bar.style.setProperty("--dummy100", 0);
    bar.style.setProperty("--dummy101", 0);
    bar.style.setProperty("--dummy102", 0);
    bar.style.setProperty("--dummy103", 0);
    bar.style.setProperty("--dummy104", 0);
    bar.style.setProperty("--dummy105", 0);
    bar.style.setProperty("--dummy106", 0);
    bar.style.setProperty("--dummy107", 0);
    bar.style.setProperty("--dummy108", 0);
    bar.style.setProperty("--dummy109", 0);
    bar.style.setProperty("--dummy110", 0);
    bar.style.setProperty("--dummy111", 0);
    bar.style.setProperty("--dummy112", 0);
    bar.style.setProperty("--dummy113", 0);
    bar.style.setProperty("--dummy114", 0);
    bar.style.setProperty("--dummy115", 0);
    bar.style.setProperty("--dummy116", 0);
    bar.style.setProperty("--dummy117", 0);
    bar.style.setProperty("--dummy118", 0);
    bar.style.setProperty("--dummy119", 0);
    bar.style.setProperty("--dummy120", 0);
    bar.style.setProperty("--dummy121", 0);
    bar.style.setProperty("--dummy122", 0);
    bar.style.setProperty("--dummy123", 0);
    bar.style.setProperty("--dummy124", 0);
    bar.style.setProperty("--dummy125", 0);
    bar.style.setProperty("--dummy126", 0);
    bar.style.setProperty("--dummy127", 0);
    bar.style.setProperty("--dummy128", 0);
    bar.style.setProperty("--dummy129", 0);
    bar.style.setProperty("--dummy130", 0);
    bar.style.setProperty("--dummy131", 0);
    bar.style.setProperty("--dummy132", 0);
    bar.style.setProperty("--dummy133", 0);
    bar.style.setProperty("--dummy134", 0);
    bar.style.setProperty("--dummy135", 0);
    bar.style.setProperty("--dummy136", 0);
    bar.style.setProperty("--dummy137", 0);
    bar.style.setProperty("--dummy138", 0);
    bar.style.setProperty("--dummy139", 0);
    bar.style.setProperty("--dummy140", 0);
    bar.style.setProperty("--dummy141", 0);
    bar.style.setProperty("--dummy142", 0);
    bar.style.setProperty("--dummy143", 0);
    bar.style.setProperty("--dummy144", 0);
    bar.style.setProperty("--dummy145", 0);
    bar.style.setProperty("--dummy146", 0);
    bar.style.setProperty("--dummy147", 0);
    bar.style.setProperty("--dummy148", 0);
    bar.style.setProperty("--dummy149", 0);
    bar.style.setProperty("--dummy150", 0);
    bar.style.setProperty("--dummy151", 0);
    bar.style.setProperty("--dummy152", 0);
    bar.style.setProperty("--dummy153", 0);
    bar.style.setProperty("--dummy154", 0);
    bar.style.setProperty("--dummy155", 0);
    bar.style.setProperty("--dummy156", 0);
    bar.style.setProperty("--dummy157", 0);
    bar.style.setProperty("--dummy158", 0);
    bar.style.setProperty("--dummy159", 0);
    bar.style.setProperty("--dummy160", 0);
    bar.style.setProperty("--dummy161", 0);
    bar.style.setProperty("--dummy162", 0);
    bar.style.setProperty("--dummy163", 0);
    bar.style.setProperty("--dummy164", 0);
    bar.style.setProperty("--dummy165", 0);
    bar.style.setProperty("--dummy166", 0);
    bar.style.setProperty("--dummy167", 0);
    bar.style.setProperty("--dummy168", 0);
    bar.style.setProperty("--dummy169", 0);
    bar.style.setProperty("--dummy170", 0);
    bar.style.setProperty("--dummy171", 0);
    bar.style.setProperty("--dummy172", 0);
    bar.style.setProperty("--dummy173", 0);
    bar.style.setProperty("--dummy174", 0);
    bar.style.setProperty("--dummy175", 0);
    bar.style.setProperty("--dummy176", 0);
    bar.style.setProperty("--dummy177", 0);
    bar.style.setProperty("--dummy178", 0);
    bar.style.setProperty("--dummy179", 0);
    bar.style.setProperty("--dummy180", 0);
    bar.style.setProperty("--dummy181", 0);
    bar.style.setProperty("--dummy182", 0);
    bar.style.setProperty("--dummy183", 0);
    bar.style.setProperty("--dummy184", 0);
    bar.style.setProperty("--dummy185", 0);
    bar.style.setProperty("--dummy186", 0);
    bar.style.setProperty("--dummy187", 0);
    bar.style.setProperty("--dummy188", 0);
    bar.style.setProperty("--dummy189", 0);
    bar.style.setProperty("--dummy190", 0);
    bar.style.setProperty("--dummy191", 0);
    bar.style.setProperty("--dummy192", 0);
    bar.style.setProperty("--dummy193", 0);
    bar.style.setProperty("--dummy194", 0);
    bar.style.setProperty("--dummy195", 0);
    bar.style.setProperty("--dummy196", 0);
    bar.style.setProperty("--dummy197", 0);
    bar.style.setProperty("--dummy198", 0);
    bar.style.setProperty("--dummy199", 0);
    bar.style.setProperty("--dummy200", 0);
  }, 800);
});

/* Modals */
document.querySelectorAll(".project-card").forEach(card => {
  card.onclick = () => {
    document.getElementById(card.dataset.modal).style.display = "flex";
  };
});
document.querySelectorAll(".close").forEach(btn => {
  btn.onclick = () => btn.closest(".modal").style.display = "none";
});

/* Year */
document.getElementById("year").textContent = new Date().getFullYear();
